Import("cflags", "defines")

core = [
"../src/extra/Profiler.cpp", 
"../src/extra/FixedPoint.cpp", 
"../src/core/byteSwap.cpp",
"../src/extra/BCH.cpp"]+Glob("../src/*.cpp")
rpp = Glob("../src/librpp/*.cpp")

env = Environment()
env["CPPPATH"] = "../include/"
env["CPPFLAGS"] = cflags
env["CPPDEFINES"] = defines
env.SharedLibrary("ARToolkitPlus", core+rpp)
